# Generated by Django 2.2.7 on 2020-02-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_v1', '0002_auto_20200224_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probability',
            name='guess_probability',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='probability',
            name='prior_probability',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='probability',
            name='slip_probability',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='probability',
            name='transition_probability',
            field=models.FloatField(),
        ),
    ]
