# Generated by Django 2.2.7 on 2020-03-07 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_v1', '0003_auto_20200224_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theta', models.FloatField()),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor_v1.Skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor_v1.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Irt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discrimination', models.FloatField()),
                ('difficulty', models.FloatField()),
                ('pseudo_guess', models.FloatField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor_v1.Problem')),
            ],
        ),
    ]
