# Generated by Django 2.2.7 on 2020-03-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_v1', '0004_irt_skillstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='irt',
            name='asymptote',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
