# Generated by Django 2.2.7 on 2020-03-09 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_v1', '0005_irt_asymptote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentresponse',
            old_name='problem_id',
            new_name='problem',
        ),
        migrations.RenameField(
            model_name='studentresponse',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RemoveField(
            model_name='studentresponse',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='studentresponse',
            name='test_type',
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='time_taken',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='ResponseSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor_v1.Problem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor_v1.Student')),
            ],
        ),
    ]
