# Generated by Django 2.2.7 on 2020-03-09 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_v1', '0006_auto_20200309_0825'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResponseSequence',
        ),
    ]
